version: 0.0
os: linux
files:
  - source: /
    destination: /home/deploy/mvp-1oh1
permissions:
  - object: /home/deploy/mvp-1oh1
    owner: deploy
    group: deploy
    pattern: "*"
    mode: 775
    type:
      - file
      - directory
hooks:
  BeforeInstall:
    - location: deployment_scripts/arrange-deployment-folders.sh
      runas: root
  AfterInstall:
    - location: deployment_scripts/db-config.sh
      runas: deploy
    - location: deployment_scripts/install-gems.sh
      runas: deploy
    - location: deployment_scripts/compile-assets.sh
      runas: deploy
    - location: deployment_scripts/run-db-migrations.sh
      runas: deploy

  ApplicationStart:
    - location: deployment_scripts/finish-installation.sh
      runas: root
