# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.5.1

pipelines:
  branches:
    master:
      - step:
          script:
            # - apt-get update # required to install zip
            # - apt-get install -y zip # required for packaging up the application
            # - pip install boto3==1.3.0 # required for codedeploy_deploy.py
            # - zip -r /tmp/artifact.zip * # package up the application for deployment
            # - python codedeploy_deploy.py # run the deployment script
